/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsNewRouteImport } from './routes/cars.new'
import { Route as ExchangesIndexRouteImport } from './routes/exchanges.index'
import { Route as ExchangesNewRouteImport } from './routes/exchanges.new'
import { Route as CarsIdIndexRouteImport } from './routes/cars.$id.index'
import { Route as CarsIdEditRouteImport } from './routes/cars.$id.edit'
import { Route as ExchangesIdIndexRouteImport } from './routes/exchanges.$id.index'
import { Route as ExchangesIdEditRouteImport } from './routes/exchanges.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsNewRoute = CarsNewRouteImport.update({
  id: '/cars/new',
  path: '/cars/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesIndexRoute = ExchangesIndexRouteImport.update({
  id: '/exchanges/',
  path: '/exchanges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesNewRoute = ExchangesNewRouteImport.update({
  id: '/exchanges/new',
  path: '/exchanges/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdIndexRoute = CarsIdIndexRouteImport.update({
  id: '/cars/$id/',
  path: '/cars/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdEditRoute = CarsIdEditRouteImport.update({
  id: '/cars/$id/edit',
  path: '/cars/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesIdIndexRoute = ExchangesIdIndexRouteImport.update({
  id: '/exchanges/$id/',
  path: '/exchanges/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesIdEditRoute = ExchangesIdEditRouteImport.update({
  id: '/exchanges/$id/edit',
  path: '/exchanges/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars/new': typeof CarsNewRoute
  '/exchanges/new': typeof ExchangesNewRoute
  '/cars/': typeof CarsIndexRoute
  '/exchanges/': typeof ExchangesIndexRoute
  '/cars/$id/edit': typeof CarsIdEditRoute
  '/exchanges/$id/edit': typeof ExchangesIdEditRoute
  '/cars/$id/': typeof CarsIdIndexRoute
  '/exchanges/$id/': typeof ExchangesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars/new': typeof CarsNewRoute
  '/exchanges/new': typeof ExchangesNewRoute
  '/cars': typeof CarsIndexRoute
  '/exchanges': typeof ExchangesIndexRoute
  '/cars/$id/edit': typeof CarsIdEditRoute
  '/exchanges/$id/edit': typeof ExchangesIdEditRoute
  '/cars/$id': typeof CarsIdIndexRoute
  '/exchanges/$id': typeof ExchangesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars/new': typeof CarsNewRoute
  '/exchanges/new': typeof ExchangesNewRoute
  '/cars/': typeof CarsIndexRoute
  '/exchanges/': typeof ExchangesIndexRoute
  '/cars/$id/edit': typeof CarsIdEditRoute
  '/exchanges/$id/edit': typeof ExchangesIdEditRoute
  '/cars/$id/': typeof CarsIdIndexRoute
  '/exchanges/$id/': typeof ExchangesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars/new'
    | '/exchanges/new'
    | '/cars/'
    | '/exchanges/'
    | '/cars/$id/edit'
    | '/exchanges/$id/edit'
    | '/cars/$id/'
    | '/exchanges/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cars/new'
    | '/exchanges/new'
    | '/cars'
    | '/exchanges'
    | '/cars/$id/edit'
    | '/exchanges/$id/edit'
    | '/cars/$id'
    | '/exchanges/$id'
  id:
    | '__root__'
    | '/'
    | '/cars/new'
    | '/exchanges/new'
    | '/cars/'
    | '/exchanges/'
    | '/cars/$id/edit'
    | '/exchanges/$id/edit'
    | '/cars/$id/'
    | '/exchanges/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsNewRoute: typeof CarsNewRoute
  ExchangesNewRoute: typeof ExchangesNewRoute
  CarsIndexRoute: typeof CarsIndexRoute
  ExchangesIndexRoute: typeof ExchangesIndexRoute
  CarsIdEditRoute: typeof CarsIdEditRoute
  ExchangesIdEditRoute: typeof ExchangesIdEditRoute
  CarsIdIndexRoute: typeof CarsIdIndexRoute
  ExchangesIdIndexRoute: typeof ExchangesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/new': {
      id: '/cars/new'
      path: '/cars/new'
      fullPath: '/cars/new'
      preLoaderRoute: typeof CarsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges/': {
      id: '/exchanges/'
      path: '/exchanges'
      fullPath: '/exchanges/'
      preLoaderRoute: typeof ExchangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges/new': {
      id: '/exchanges/new'
      path: '/exchanges/new'
      fullPath: '/exchanges/new'
      preLoaderRoute: typeof ExchangesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id/': {
      id: '/cars/$id/'
      path: '/cars/$id'
      fullPath: '/cars/$id/'
      preLoaderRoute: typeof CarsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id/edit': {
      id: '/cars/$id/edit'
      path: '/cars/$id/edit'
      fullPath: '/cars/$id/edit'
      preLoaderRoute: typeof CarsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges/$id/': {
      id: '/exchanges/$id/'
      path: '/exchanges/$id'
      fullPath: '/exchanges/$id/'
      preLoaderRoute: typeof ExchangesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges/$id/edit': {
      id: '/exchanges/$id/edit'
      path: '/exchanges/$id/edit'
      fullPath: '/exchanges/$id/edit'
      preLoaderRoute: typeof ExchangesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsNewRoute: CarsNewRoute,
  ExchangesNewRoute: ExchangesNewRoute,
  CarsIndexRoute: CarsIndexRoute,
  ExchangesIndexRoute: ExchangesIndexRoute,
  CarsIdEditRoute: CarsIdEditRoute,
  ExchangesIdEditRoute: ExchangesIdEditRoute,
  CarsIdIndexRoute: CarsIdIndexRoute,
  ExchangesIdIndexRoute: ExchangesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
